Now let's see your photos
Predicted:  d o g
Tensor: tensor([[0.0317, 0.0728]], grad_fn=<AddmmBackward0>)
Predicted:  d o g
Tensor: tensor([[0.0424, 0.0865]], grad_fn=<AddmmBackward0>)
Traceback (most recent call last):
  File "D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\main.py", line 104, in <module>
    img_tensor = load_image(s)
  File "D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\main.py", line 89, in load_image
    img = Image.open(path)
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\PIL\Image.py", line 3469, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Backup\\Less Important\\My programs\\Git\\ML\\Models\\CNN\\dogs_vs_cats\\img\\dog2.jpd'
Traceback (most recent call last):
  File "D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\main.py", line 104, in <module>
    img_tensor = load_image(s)
  File "D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\main.py", line 89, in load_image
    img = Image.open(path)
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\PIL\Image.py", line 3469, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Backup\\Less Important\\My programs\\Git\\ML\\Models\\CNN\\dogs_vs_cats\\img\\dog2.jpd'
